### ISSUE TITLE
[WS] Invalid URL: undefined on sandbox

### ISSUE THREAD

**Issue by JavAster** [escwdev/kucoin-node-api#29]
Hi. Thanks for awesome library !

I experienced a bug when trying to api.initSocket (topic: orders) when connecting to sandbox. 
Error:
`
TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    at new NodeError (node:internal/errors:329:5)
    at onParseError (node:internal/url:282:9)
    at new URL (node:internal/url:358:5)
    at initAsClient (/xxx/node_modules/kucoin-node-api/node_modules/ws/lib/websocket.js:484:27)
    at new WebSocket (/xxx/node_modules/kucoin-node-api/node_modules/ws/lib/websocket.js:70:7)
    at Object.Sockets.initSocket (/xxx/node_modules/kucoin-node-api/lib/websockets.js:58:14)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}
`

**Comment by JavAster** [comment]
Ah, my bad. Environment should be defined as 'sandbox'. Kucoin.js just had }else{ so I though it takes anything, even undefined :p
